DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294541
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294534
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294528
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =293884
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294640
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =299882
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =290450
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =296016
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =296019
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =297687
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294667
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294689
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294677
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294680
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294684
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =294687
DELETE FROM InitiativeActions WHERE InitiativeActions.Id =298877

UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51421
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52059
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51961
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51963
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51972
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51968
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51967
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51969
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51970
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51971
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51973
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51974
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51975
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51976
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51977
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51979
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51980
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51981
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51982
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51983
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51984
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51985
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51987
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51990
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51993
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51994
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51995
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51996
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51997
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51998
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=51999
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52000
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52001
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52004
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52005
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52006
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52007
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52008
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52009
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52011
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52012
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52013
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52014
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52015
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52016
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52017
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52018
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52019
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52022
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52023
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52024
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52025
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52026
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52027
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52028
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53242
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52058
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52061
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52066
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52069
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52070
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52071
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52072
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52073
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52074
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52075
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52076
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52077
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52078
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52082
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52086
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52087
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52088
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52091
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52092
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52094
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52099
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52102
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52110
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52111
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52131
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52133
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52135
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52140
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=52143
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53144
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53145
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53146
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53147
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53148
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53149
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53150
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53151
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53152
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53153
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53154
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53155
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53157
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53160
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53162
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53167
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53168
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53169
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53170
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53171
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53172
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53175
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53176
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53177
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53178
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53179
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53180
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53181
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53182
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53183
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53185
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53186
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53189
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53190
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53191
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53193
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53194
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53196
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53197
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53198
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53199
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53203
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53204
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53210
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53216
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53220
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53221
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53222
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53223
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53226
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53227
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53230
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53231
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53233
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53234
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53241
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53243
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53244
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53248
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53249
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53250
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53251
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53252
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53253
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53257
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53258
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53262
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53263
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53266
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53267
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53269
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53270
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53271
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53272
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53275
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53276
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53278
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53281
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53282
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53283
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53284
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53285
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53290
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53294
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53301
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53303
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53305
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53306
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53318
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53321
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53322
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53323
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53324
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53325
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53326
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53327
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53328
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53331
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53335
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53349
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53392
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53354
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53364
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53370
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53371
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53375
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53386
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53395
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53394
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53400
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53406
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53421
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53496
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53497
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53528
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53542
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53544
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53546
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53562
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53564
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53574
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53580
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53585
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53586
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53587
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53588
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53589
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53590
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53605
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53595
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53596
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53598
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53599
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53600
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53603
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53604
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53610
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53616
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53617
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53618
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53619
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53622
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53625
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53627
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53651
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53653
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53654
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53655
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53659
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53660
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53661
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53662
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53663
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53664
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53665
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53666
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53667
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53668
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53669
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53670
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53671
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53672
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53673
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53674
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53676
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=53678
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=60582
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=60454
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=60732
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=60778
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=61858
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=62055
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=62067
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=64787
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=65367
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=69222
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=69258
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=69482
UPDATE [dbo].[DetailInformations] SET [ProjectEngineer] =NULL Where Id=69921
